name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      if: github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: |
        cd home_energy
        docker build . --file Dockerfile --tag ghcr.io/stuartleeks/myenergi:latest

    - name: Push the Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/stuartleeks/myenergi:latest
